### ISSUE TITLE
study TDengine

### ISSUE THREAD

**Issue by bourbonkk** [Clymene-project/Clymene#31]

**Comment by sangshuduo** [comment]
Clymene is really cool!

I notice it supports Prometheus, OpenTSDB, and other databases data writing. Actually, we TDengine also support OpenTSDB line protocol data writing and Prometheus remote_write interface. Pls, check out the document from https://github.com/taosdata/taosadapter. 

Please feel free to let me know what I can help with.

**Comment by bourbonkk** [comment]
> Clymene is really cool!
> 
> I notice it supports Prometheus, OpenTSDB, and other databases data writing. Actually, we TDengine also support OpenTSDB line protocol data writing and Prometheus remote_write interface. Pls, check out the document from https://github.com/taosdata/taosadapter.
> 
> Please feel free to let me know what I can help with.

Thank you for your interest in Climene.
The v1.3.0 release adds influxdb.
I will add TDengine to the roadmap so that it can be used in Clymene.

**Comment by bourbonkk** [comment]
hi  @sangshuduo, 
I am currently developing to store prometheus time series data in tdengine using taosdapter.
While building the taosdata driver-go, an error stating that taos.h does not exist is occurring. There seems to be an issue in 2019.
Can you help me?
![image](https://user-images.githubusercontent.com/25188468/150349239-5c0f2dcf-8748-4c14-b7fd-7c4606b6e850.png)

**Comment by bourbonkk** [comment]
@sangshuduo plz, check if this is the right way to use
https://github.com/Clymene-project/Clymene/commit/6bbb10c7a2b8431f987abb8f063dde4c79e005b4

**Comment by bourbonkk** [comment]
Okay, I got it. I'll make it Golang.

**Comment by sangshuduo** [comment]
sorry for the late reply. please feel free to raise issues with us on our GitHub repository. Our colleague might be also notified and answer your question early.
